parameters:
#    striide_web.example.class: Striide\WebBundle\Example

services:
  striide_web.twig.markup.extension:
    class: Striide\WebBundle\Extension\MarkupExtension
    calls:
      - [ setKernel, [@kernel]]
      - [ setRouter, [@router]]
      - [ setDomainName, [%domain_name%] ]
    tags:
      - { name: twig.extension }
  striide_web.twig.data.extension:
    class: Striide\WebBundle\Extension\DataExtension
    tags:
      - { name: twig.extension }
